-- 029: controle financeiro das agências e operadoras (dono, 10/10/2026)
-- Reservas da agência (vêm do Silbeck pelo código da empresa), faturas fechadas por período e pagamentos
-- (sinal e fatura). Valores sobre o líquido: a comissão já vem descontada. Pode rodar de novo sem estragar nada.
create table if not exists agencia_faturas (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity,
  agencia_id uuid not null references agencias(id) on delete cascade,
  periodo_ini date not null,
  periodo_fim date not null,
  emitida_em date not null default current_date,
  vencimento date not null,
  valor numeric(12,2) not null,                       -- soma dos saldos (líquido menos o sinal pago) das reservas
  situacao text not null default 'aberta' check (situacao in ('aberta', 'paga', 'cancelada')),
  observacoes text,
  criado_por uuid references usuarios(id) on delete set null,
  criado_em timestamptz not null default now()
);
create index if not exists agencia_faturas_agencia on agencia_faturas (agencia_id, situacao);

create table if not exists agencia_reservas (
  id uuid primary key default gen_random_uuid(),
  agencia_id uuid not null references agencias(id) on delete cascade,
  silbeck_id text not null unique,                    -- número da reserva no Silbeck
  origem text not null default 'silbeck',             -- silbeck (motor, balcão) ou crm
  titular text,
  acomodacao text,
  data_entrada date,
  data_saida date,
  valor_total numeric(12,2) not null default 0,       -- diárias (hospedagem)
  comissao_pct numeric(5,2),
  valor_liquido numeric(12,2) not null default 0,     -- o que a agência paga (total menos a comissão)
  sinal_previsto numeric(12,2) not null default 0,
  sinal_pago numeric(12,2) not null default 0,        -- adiantamentos ativos no Silbeck
  status_silbeck int,
  status_descricao text,
  cancelada boolean not null default false,
  fatura_id uuid references agencia_faturas(id) on delete set null,
  sincronizado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);
create index if not exists agencia_reservas_agencia on agencia_reservas (agencia_id, data_saida);

create table if not exists agencia_pagamentos (
  id uuid primary key default gen_random_uuid(),
  agencia_id uuid not null references agencias(id) on delete cascade,
  tipo text not null check (tipo in ('sinal', 'fatura')),
  agencia_reserva_id uuid references agencia_reservas(id) on delete set null,
  fatura_id uuid references agencia_faturas(id) on delete set null,
  valor numeric(12,2) not null check (valor > 0),
  data date not null,
  forma text,                                         -- pix, transferencia, boleto, cartao, dinheiro, outro
  observacao text,
  silbeck_adiantamento_id text,                       -- sinal lançado no Silbeck pelo CRM
  criado_por uuid references usuarios(id) on delete set null,
  criado_em timestamptz not null default now()
);
create index if not exists agencia_pagamentos_agencia on agencia_pagamentos (agencia_id, data);

alter table agencia_faturas enable row level security;
alter table agencia_reservas enable row level security;
alter table agencia_pagamentos enable row level security;
drop policy if exists "equipe le agencia_faturas" on agencia_faturas;
create policy "equipe le agencia_faturas" on agencia_faturas for select to authenticated using (usuario_ativo());
drop policy if exists "equipe le agencia_reservas" on agencia_reservas;
create policy "equipe le agencia_reservas" on agencia_reservas for select to authenticated using (usuario_ativo());
drop policy if exists "equipe le agencia_pagamentos" on agencia_pagamentos;
create policy "equipe le agencia_pagamentos" on agencia_pagamentos for select to authenticated using (usuario_ativo());
